# Generated by Django 3.2.12 on 2022-11-23 08:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=10)),
                ('running_time', models.IntegerField()),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('genre_ids', models.IntegerField()),
                ('genres', models.JSONField(default=list)),
                ('poster_path', models.TextField()),
                ('backdrop_path', models.TextField(null=True)),
                ('popularity', models.FloatField()),
                ('actual_vote_average', models.FloatField()),
                ('man_vote', models.FloatField()),
                ('woman_vote', models.FloatField()),
                ('vote_10', models.FloatField()),
                ('vote_20', models.FloatField()),
                ('vote_30', models.FloatField()),
                ('vote_40', models.FloatField()),
                ('vote_50', models.FloatField()),
                ('grade', models.IntegerField()),
                ('actors', models.CharField(max_length=100)),
                ('video_url', models.TextField()),
                ('profile', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
