# -*- coding: utf-8 -*-
"""Untitled88.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HW99XUS0pJDzGeIHsxGGCVrKaggScHl3
"""

# !pip install requests

import requests

date = ['20220501','20220601','20220701','20220801','20220901','20221001','20221101']

title_list = set()

for d in date:

    url = f'https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key=01d6af266369c5a5a496ef0f24fcff46&targetDt={d}'

    response = requests.get(url).json()

    for item in response['boxOfficeResult']['weeklyBoxOfficeList']:
        
        title_list.add(item['movieNm'])

print(title_list)

